import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],
  resudentsSidebar: [{type: 'autogenerated', dirName: 'residents'}],
  faqSidebar: [{type: 'autogenerated', dirName: 'faq'}]  
};

export default sidebars;
